import Head from 'next/head'
import Script from 'next/script'

const HeadAppComponent = () => {
    return (
        <Head>
            <title>Curriculum</title>
            <meta name="description" content="Generated by create next app" />

            <meta name="viewport" content="width=device-width, initial-scale=1.0" />

            <link rel="icon" href="/favicon.ico" />

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
            {/*<!-- Add the slick-theme.css if you want default styling -->*/}
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
            {/*<!-- Add the slick-theme.css if you want default styling -->*/}
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />

        </Head>
    )
}
export default HeadAppComponent;